x-service-base: &service-base
  restart: always
  env_file: .env
  depends_on:
    mongodb:
      condition: service_healthy

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  create-service:
    <<: *service-base
    build: ./create-service
    container_name: create_service
    ports:
      - "8080:8080"

  read-service:
    <<: *service-base
    build: ./read-service
    container_name: read_service
    ports:
      - "8081:8081"

  update-service:
    <<: *service-base
    build: ./update-service
    container_name: update_service
    ports:
      - "8082:8082"

  delete-service:
    <<: *service-base
    build: ./delete-service
    container_name: delete_service
    ports:
      - "8083:8083"

  data-analysis:
    <<: *service-base
    build:
      context: ./data-analysis
    container_name: data_analysis
    ports:
      - "8084:8084"

  create-service-dev:
    build:
      context: ./create-service
      target: builder
    working_dir: /app
    volumes:
      - ./create-service:/app
    stdin_open: true
    tty: true
    profiles: [ "dev" ]

  read-service-dev:
    build:
      context: ./read-service
      target: builder
    working_dir: /app
    volumes:
      - ./read-service:/app
    stdin_open: true
    tty: true
    profiles: [ "dev" ]

  update-service-dev:
    build:
      context: ./update-service
      target: builder
    working_dir: /app
    volumes:
      - ./update-service:/app
    stdin_open: true
    tty: true
    profiles: [ "dev" ]

  delete-service-dev:
    build:
      context: ./delete-service
      target: builder
    working_dir: /app
    volumes:
      - ./delete-service:/app
    stdin_open: true
    tty: true
    profiles: [ "dev" ]

  data-analysis-dev:
    build:
      context: ./data-analysis
      target: builder
    working_dir: /app
    volumes:
      - ./data-analysis:/app
    stdin_open: true
    tty: true
    profiles: [ "dev" ]

volumes:
  mongo_data:
