#!/bin/bash
# newman-report.sh
# Parses Newman JSON report and writes test metrics to /tmp/sonar-metrics.env.
# Requires /tmp/newman-results.json generated by the Black-box Tests stage.

set -e

NEWMAN_JSON="/tmp/newman-results.json"
METRICS_FILE="/tmp/sonar-metrics.env"

if [ ! -f "$NEWMAN_JSON" ]; then
    echo "[newman] WARN - newman-results.json not found, writing defaults"
    echo "NEWMAN_TOTAL=0"    >> "$METRICS_FILE"
    echo "NEWMAN_PASSED=0"   >> "$METRICS_FILE"
    echo "NEWMAN_FAILED=0"   >> "$METRICS_FILE"
    echo "NEWMAN_REQUESTS=0" >> "$METRICS_FILE"
    exit 0
fi

# Extract assertions stats
NEWMAN_TOTAL=$(grep -A4 '"assertions"' "$NEWMAN_JSON" \
    | grep '"total"' | head -1 \
    | awk -F':' '{print $2}' | tr -d ' ,')

NEWMAN_FAILED=$(grep -A4 '"assertions"' "$NEWMAN_JSON" \
    | grep '"failed"' | head -1 \
    | awk -F':' '{print $2}' | tr -d ' ,')

NEWMAN_REQUESTS=$(grep -A4 '"items"' "$NEWMAN_JSON" \
    | grep '"total"' | head -1 \
    | awk -F':' '{print $2}' | tr -d ' ,')

# Apply defaults for missing values
NEWMAN_TOTAL=${NEWMAN_TOTAL:-0}
NEWMAN_FAILED=${NEWMAN_FAILED:-0}
NEWMAN_REQUESTS=${NEWMAN_REQUESTS:-0}

# Calculate passed
NEWMAN_PASSED=$((NEWMAN_TOTAL - NEWMAN_FAILED))

# Write to metrics file
echo "NEWMAN_TOTAL=${NEWMAN_TOTAL}"       >> "$METRICS_FILE"
echo "NEWMAN_PASSED=${NEWMAN_PASSED}"     >> "$METRICS_FILE"
echo "NEWMAN_FAILED=${NEWMAN_FAILED}"     >> "$METRICS_FILE"
echo "NEWMAN_REQUESTS=${NEWMAN_REQUESTS}" >> "$METRICS_FILE"

echo "[newman] Total: ${NEWMAN_TOTAL} | Passed: ${NEWMAN_PASSED} | Failed: ${NEWMAN_FAILED} | Requests: ${NEWMAN_REQUESTS}"